#!/bin/sh
# Copyright (c) 2013 Jason LuBean - http://github.com/jlubean/kp

process_name=$1;
if [ -z "$process_name" -a "${process_name+xxx}" = "xxx" ]; then echo "Usage: kp [process_name]\n"; exit 1; fi

process_count=`ps -fe | grep $process_name | tr -s ' ' | cut -d" " -f2 | tr " " "\n" | wc | tr -s ' ' | sed 's/^ *//g' | cut -d" " -f1`
process_count=`expr $process_count - 3`

if [ $process_count -gt 0 ]
then
  while true; do
   
    if [ "${2:-}" = "Y" ]; then
      prompt="YES|no|list"
      default=Y
    elif [ "${2:-}" = "N" ]; then
      prompt="yes|NO|list"
      default=N
    elif [ "${2:-}" = "L" ]; then
      prompt="yes|no|LIST"
      default=L
    else
      prompt="yes|no|list"
      default=
    fi
  
    # Ask the question
    read -p "Are you sure you want to kill $process_count $process_name processes [$prompt]? " REPLY
  
    # Default?
    if [ -z "$REPLY" ]; then
      REPLY=$default
    fi
   
    # Check if the reply is valid
    case "$REPLY" in
      Y*|y*) ps -fe | grep $process_name | tr -s ' ' | cut -d" " -f2 | head -$process_count | tr "\n" " " | xargs sudo kill -9; echo "Killed $process_count processes."; exit;;
      N*|n*) exit;;
      L*|l*) ps -fe | grep $process_name | head -$process_count;;
    esac
  done
else
  echo "No $process_name processes found."
fi
