#!/bin/sh
# Copyright (c) 2013 Jason LuBean - http://github.com/jlubean/kp
# Kill all processes that have a particular key word in the command used to initiate them.
# Usage: kp [key_word]
#

key_word=$1;
if [ -z "key_word" -a "${key_word+xxx}" = "xxx" ]; then echo "Usage: kp [key_word]\n"; exit 1; fi

process_count=`ps -fe | grep $key_word | tr -s ' ' | cut -d" " -f2 | tr " " "\n" | wc | tr -s ' ' | sed 's/^ *//g' | cut -d" " -f1`
process_count=`expr $process_count - 3`
default="L"
prompt="yes|no|List"

if [ $process_count -gt 0 ]
then
  while true; do
   
    # Ask the question
    read -p "Are you sure you want to kill $process_count $key_word processes [$prompt]? " REPLY
  
    # Default?
    if [ -z "$REPLY" ]; then
      REPLY=$default
    fi
   
    # Check if the reply is valid
    case "$REPLY" in
      Y*|y*) ps -fe | grep $key_word | tr -s ' ' | cut -d" " -f2 | head -$process_count | tr "\n" " " | xargs sudo kill -9; echo "Killed $process_count processes."; exit;;
      N*|n*) echo "No processes were killed."; exit;;
      L*|l*) ps -fe | grep $key_word | head -$process_count;;
    esac
  done
else
  echo "No $key_word processes found."
fi
