#!/bin/sh

process_name=$1;
if [ -z "$process_name" -a "${process_name+xxx}" = "xxx" ]; then echo "Usage: kp [process_name]\n"; exit 1; fi

process_count=`ps -fe | grep $process_name | tr -s ' ' | cut -d" " -f2 | tr " " "\n" | wc | tr -s ' ' | sed 's/^ *//g' | cut -d" " -f1`
process_count=`expr $process_count - 3`
if [ $process_count -gt 0 ]
then
  echo "Killing $process_count $process_name processes..."
  ps -fe | grep $process_name | tr -s ' ' | cut -d" " -f2 | head -$process_count | tr "\n" " " | xargs sudo kill -9
  echo "Done killing processes."
else
  echo "No $process_name processes found."
fi
